(function() {
  const crcTable = (() => { const table = new Uint32Array(256); for (let i = 0; i < 256; i++) { let value = i; for (let bit = 0; bit < 8; bit++) value = value & 1 ? 0xEDB88320 ^ value >>> 1 : value >>> 1; table[i] = value; } return table; })();
  const word = value => Uint8Array.of(value >>> 24, value >>> 16 & 255, value >>> 8 & 255, value & 255);
  function chunk(type, data) { const name = Uint8Array.from(type, char => char.charCodeAt(0)), crcData = new Uint8Array(name.length + data.length), out = new Uint8Array(data.length + 12); crcData.set(name); crcData.set(data, name.length); let crc = 0xFFFFFFFF; for (const byte of crcData) crc = crcTable[(crc ^ byte) & 255] ^ crc >>> 8; out.set(word(data.length)); out.set(name, 4); out.set(data, 8); out.set(word((crc ^ 0xFFFFFFFF) >>> 0), data.length + 8); return out; }
  async function compress(data) { const stream = new CompressionStream('deflate'), compressed = new Response(stream.readable).arrayBuffer(), writer = stream.writable.getWriter(); await writer.write(data); await writer.close(); return new Uint8Array(await compressed); }
  function bounds(image) { const {data, width, height} = image; let left = width, top = height, right = -1, bottom = -1; for (let y = 0, pixel = 0; y < height; y++) for (let x = 0; x < width; x++, pixel++) if (data[pixel * 4 + 3] > 8) { left = Math.min(left, x); top = Math.min(top, y); right = Math.max(right, x); bottom = Math.max(bottom, y); } return right < left ? null : {left, top, right, bottom}; }
  async function framesFor(options, status) {
    const width = Math.max(32, Math.min(3840, Math.round(options.width))), height = Math.max(32, Math.min(2160, Math.round(options.height))), fps = Math.max(1, Math.min(60, Math.round(options.fps))), duration = Math.max(.1, Math.min(120, Number(options.duration))), canvas = document.createElement('canvas'); canvas.width = width; canvas.height = height;
    const ctx = canvas.getContext('2d', {alpha:true}), system = new ParticleSystem(canvas, ctx, {assetBaseUrl:'images/particleemu/'}), config = parseGS2ParticleCode(window.ParticleEmuRuntime.getParticleCode()); if (!config) throw new Error('Could not parse a particle emitter from the current code.'); config.x = 0; config.y = 0; await system.createEmitter(config);
    const count = Math.max(1, Math.round(duration * fps)), step = 1 / fps, rendered = [], allBounds = [];
    for (let index = 0; index < count; index++) { ctx.clearRect(0, 0, width, height); system.emitters.forEach(emitter => emitter.update(step, (index + 1) * step)); ctx.save(); ctx.translate(width / 2, height / 2); system.draw(ctx); ctx.restore(); const image = ctx.getImageData(0, 0, width, height), frameBounds = bounds(image); allBounds.push(frameBounds); rendered.push(frameBounds ? ctx.getImageData(frameBounds.left, frameBounds.top, frameBounds.right - frameBounds.left + 1, frameBounds.bottom - frameBounds.top + 1) : null); status.textContent = `Rendering frame ${index + 1}/${count}`; if ((index & 3) === 3) await new Promise(resolve => requestAnimationFrame(resolve)); }
    const visible = allBounds.filter(Boolean), union = visible.length ? visible.reduce((current, next) => ({left:Math.min(current.left, next.left), top:Math.min(current.top, next.top), right:Math.max(current.right, next.right), bottom:Math.max(current.bottom, next.bottom)})) : null, padding = options.crop ? 8 : 0, crop = options.crop && union ? {x:Math.max(0, union.left - padding), y:Math.max(0, union.top - padding), right:Math.min(width, union.right + padding + 1), bottom:Math.min(height, union.bottom + padding + 1)} : {x:0, y:0, right:width, bottom:height}; crop.width = crop.right - crop.x; crop.height = crop.bottom - crop.y;
    const output = document.createElement('canvas'); output.width = crop.width; output.height = crop.height; const outputCtx = output.getContext('2d'); return {width:crop.width, height:crop.height, fps, frames:rendered.map((image, index) => { outputCtx.clearRect(0, 0, crop.width, crop.height); if (options.background) { outputCtx.fillStyle = options.background; outputCtx.fillRect(0, 0, crop.width, crop.height); } const frameBounds = allBounds[index]; if (image && frameBounds) outputCtx.putImageData(image, frameBounds.left - crop.x, frameBounds.top - crop.y); return outputCtx.getImageData(0, 0, crop.width, crop.height); })};
  }
  async function apng(width, height, frames, fps, status) {
    if (!window.CompressionStream) throw new Error('Animated PNG export is not supported by this runtime.');
    const parts = [Uint8Array.of(137, 80, 78, 71, 13, 10, 26, 10), chunk('IHDR', Uint8Array.of(...word(width), ...word(height), 8, 6, 0, 0, 0)), chunk('acTL', Uint8Array.of(...word(frames.length), ...word(0)))]; let sequence = 0;
    for (let index = 0; index < frames.length; index++) { status.textContent = `Encoding PNG frame ${index + 1}/${frames.length}`; const frame = frames[index], stride = width * 4 + 1, raw = new Uint8Array(stride * height); for (let y = 0; y < height; y++) raw.set(frame.data.subarray(y * width * 4, (y + 1) * width * 4), y * stride + 1); const control = Uint8Array.of(...word(sequence++), ...word(width), ...word(height), ...word(0), ...word(0), ...word(Math.max(1, Math.round(1000 / fps))).slice(2), ...word(1000).slice(2), 0, 0); parts.push(chunk('fcTL', control)); const compressed = await compress(raw); parts.push(index ? chunk('fdAT', Uint8Array.of(...word(sequence++), ...compressed)) : chunk('IDAT', compressed)); }
    parts.push(chunk('IEND', new Uint8Array())); return new Blob(parts, {type:'image/png'});
  }
  async function save(blob) { const wails = window.__GSUITE__, filename = 'particle-effect.png'; if (wails?.dialog?.save && wails?.fs?.writeFile) { const path = await wails.dialog.save({defaultPath:filename, title:'Export Particle Animation', filters:[{name:'Animated PNG', extensions:['png']}]}); if (path) await wails.fs.writeFile(path, new Uint8Array(await blob.arrayBuffer())); return; } const url = URL.createObjectURL(blob), link = document.createElement('a'); link.href = url; link.download = filename; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
  function prepare(dialog) {
    if (dialog.dataset.apngReady) return; dialog.dataset.apngReady = 'true'; const format = dialog.querySelector('#particleExportFormat'), option = new Option('Animated PNG (smooth alpha)', 'apng'); format.add(option); const start = dialog.querySelector('#particleExportStart'), cancel = dialog.querySelector('#particleExportCancel'), status = dialog.querySelector('#particleExportStatus');
    start.addEventListener('click', async event => { if (format.value !== 'apng') return; event.preventDefault(); event.stopImmediatePropagation(); const background = dialog.querySelector('#particleExportBackground').value === 'canvas' ? (localStorage.getItem('gsuiteParticleViewportBgColor') || '#006400') : null, options = {duration:Number(dialog.querySelector('#particleExportDuration').value), fps:Number(dialog.querySelector('#particleExportFps').value), width:Number(dialog.querySelector('#particleExportWidth').value), height:Number(dialog.querySelector('#particleExportHeight').value), background, crop:dialog.querySelector('#particleExportCrop').checked}; if (!Number.isFinite(options.duration) || !Number.isFinite(options.width) || !Number.isFinite(options.height)) { status.textContent = 'Enter valid export values.'; return; } start.disabled = true; cancel.disabled = true; try { const result = await framesFor(options, status), blob = await apng(result.width, result.height, result.frames, result.fps, status); status.textContent = 'Saving export...'; await save(blob); dialog.parentElement?.remove(); } catch (error) { status.textContent = error?.message || String(error); start.disabled = false; cancel.disabled = false; } }, true);
  }
  const attach = () => { new MutationObserver(() => document.querySelectorAll('#particleExportDialog').forEach(prepare)).observe(document.body, {childList:true, subtree:true}); document.querySelectorAll('#particleExportDialog').forEach(prepare); };
  if (document.body) attach(); else document.addEventListener('DOMContentLoaded', attach, {once:true});
})();
