(function() {
    const isWailsPage = window._wails?.flags?.isGSuiteDesktop || window.location.protocol === 'wails:' || window.location.hostname === 'wails.localhost' || window.location.port === '9245';
    if (!isWailsPage) return;
    const servicePromise = import('/bindings/gsuite/appservice.js');
    const runtimePromise = import('/wails/runtime.js');
    const methods = { scan_workspace: 'ScanWorkspace', resolve_path: 'ResolvePath', load_workspace_cache: 'LoadWorkspaceCache', get_open_file_arg: 'GetOpenFileArg', register_file_associations: 'RegisterFileAssociations', check_for_update: 'CheckForUpdate', do_update: 'DoUpdate', read_text_file: 'ReadTextFile', read_file: 'ReadFile', write_text_file: 'WriteTextFile', write_file: 'WriteFile', read_dir: 'ReadDir' };
    const invoke = async (name, args = {}) => { const service = await servicePromise; const method = service[methods[name] || name]; if (typeof method !== 'function') throw new Error(`Unknown native method: ${name}`); const values = Array.isArray(args) ? args : Object.values(args || {}); return method(...values); };
    const waitForRuntime = () => runtimePromise;
    const filters = list => (list || []).map(filter => ({ DisplayName: filter.DisplayName || filter.name || 'Files', Pattern: filter.Pattern || (filter.extensions || []).map(ext => `*.${String(ext).replace(/^\*\./, '')}`).join(';') || '*.*' }));
    const unwrapDialogResult = (result, multiple) => { if (Array.isArray(result)) return multiple ? result : result[0] || null; if (typeof result === 'string') return result || null; if (Array.isArray(result?.Paths)) return multiple ? result.Paths : result.Paths[0] || null; return result?.Path || result?.path || null; };
    const openDialog = async options => { const runtime = await waitForRuntime(); const result = await runtime.Dialogs.OpenFile({ Title: options?.title || '', Directory: options?.defaultPath || '', Filters: filters(options?.filters), CanChooseDirectories: !!options?.directory, CanChooseFiles: !options?.directory, AllowsMultipleSelection: !!options?.multiple }); return unwrapDialogResult(result, !!options?.multiple); };
    const saveDialog = async options => { const runtime = await waitForRuntime(); const result = await runtime.Dialogs.SaveFile({ Title: options?.title || '', Filename: options?.defaultPath || '', Filters: filters(options?.filters) }); return unwrapDialogResult(result, false); };
    const readFile = async path => { const encoded = await invoke('read_file', { path }); if (!encoded) return new Uint8Array(); const raw = atob(encoded); const bytes = new Uint8Array(raw.length); for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i); return bytes; };
    const writeFile = async (path, data) => { const bytes = data instanceof Uint8Array ? data : new Uint8Array(data instanceof ArrayBuffer ? data : data.buffer, data.byteOffset || 0, data.byteLength || data.length); let binary = ''; for (let i = 0; i < bytes.length; i += 0x8000) binary += String.fromCharCode(...bytes.subarray(i, i + 0x8000)); return invoke('write_file', { path, encoded: btoa(binary) }); };
    const readDir = async path => { const normalized = String(path || '').replace(/^\.?[\\/]/, '').replace(/\\/g, '/').replace(/\/+$/, ''); if (normalized.toLowerCase() === 'levels') { const response = await fetch('/levels/index.json?_=' + Date.now(), { cache: 'no-store' }); if (response.ok) { const manifest = await response.json(); const files = Array.isArray(manifest) ? manifest : manifest?.files; if (Array.isArray(files)) return files.map(name => ({ name })); } } return (await invoke('read_dir', { path })).map(name => ({ name })); };
    const listen = (name, handler) => waitForRuntime().then(runtime => runtime.Events.On(name === 'wails://drag-drop' ? 'wails-file-drop' : name, event => { const data = event?.data ?? event?.payload ?? event; handler({ payload: data, data, name: event?.name || name }); }));
    const getWindow = () => ({ minimize: () => window.wails.Window.Minimise(), toggleMaximize: () => window.wails.Window.ToggleMaximise(), close: () => window.wails.Window.Close(), setTitle: title => window.wails.Window.SetTitle(title) });
    window.__GSUITE__ = { core: { invoke }, event: { listen }, fs: { readTextFile: path => invoke('read_text_file', { path }), readFile, writeTextFile: (path, content) => invoke('write_text_file', { path, content }), writeFile, readDir }, dialog: { open: openDialog, save: saveDialog }, window: { getCurrentWindow: getWindow }, updater: { check: async () => { const version = await invoke('check_for_update'); return version ? { available: true, version } : { available: false }; }, doUpdate: () => invoke('do_update') } };
})();
